In [24]:
import tflearn
from tflearn.data_utils import to_categorical, pad_sequences

In [25]:
import pandas as pd
import numpy as np
import keras
import sys
import os
from sklearn.model_selection import train_test_split

from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

In [26]:
data = pd.read_csv("reuters_final.csv")
data = data[data["Diff"] != 0]

In [31]:
df_train, df_test = train_test_split(data, test_size=0.2)

In [27]:
data= data[:3200]

In [29]:
data["Diff"] = (data['Diff'] + 1)//2

In [32]:
len(data)

3200

In [202]:
df_train

Ticker                                            Company       Open  \
62     GPI                                 Group 1 Automotive  55.000000   
56     HUM                                        Humana Inc.  66.000000   
54     TGT                                 Target Corporation  58.099998   
55     MET                                            MetLife  52.317291   
60      VZ                        Verizon Communications Inc.  34.875736   
96       F                                 Ford Motor Company   8.580000   
93    COST                       Costco Wholesale Corporation  52.000000   
99     CAT                                        Caterpillar  60.630001   
100   MSFT                              Microsoft Corporation  28.850000   
101   UNFI                               United Natural Foods  32.520000   
67      PG                     Procter & Gamble Company (The)  62.209999   
39     CAH                                    Cardinal Health  64.540001   
24      MO                                       Altria Group  79.010002   
92     ANF                        Abercrombie & Fitch Company  71.500000   
19     PFD  Flaherty & Crumrine Preferred Income Fund Inco...  16.700001   
72      CI                                  Cigna Corporation  41.663334   
33    MSFT                              Microsoft Corporation  28.330000   
28     RTN                                   Raytheon Company  50.099998   
10       F                                 Ford Motor Company   8.020000   
41      PG                     Procter & Gamble Company (The)  63.310001   
78     DIS                          Walt Disney Company (The)  31.114399   
31     CCE                    Coca-Cola European Partners plc  20.500000   
87     ENR                                 Energizer Holdings  72.300003   
80     VOD                                 Vodafone Group Plc  26.452599   
14     OMC                                 Omnicom Group Inc.  48.049999   
94     MMC                         Marsh & McLennan Companies  29.650000   
43    MSFT                              Microsoft Corporation  28.490000   
25      BA                               Boeing Company (The)  82.599998   
82     MGM                          MGM Resorts International  42.000000   
103    DUK                            Duke Energy Corporation  54.896519   
..     ...                                                ...        ...   
68      PG                     Procter & Gamble Company (The)  62.209999   
61     THC                       Tenet Healthcare Corporation  30.200001   
38     UHS                          Universal Health Services  27.010000   
11      BP                                          BP p.l.c.  67.879997   
50    MSFT                              Microsoft Corporation  28.330000   
18     COP                                     ConocoPhillips  46.615658   
3      KMB                         Kimberly-Clark Corporation  63.518696   
34   CMCSA                                Comcast Corporation  13.440000   
20      PG                     Procter & Gamble Company (The)  62.980000   
51     SYY                                  Sysco Corporation  34.369999   
52     SPG                               Simon Property Group  89.937057   
0      XOM                            Exxon Mobil Corporation  70.010002   
66     CMI                                       Cummins Inc.  32.152500   
81     BDX                                             Becton  70.250000   
86     CVS                             CVS Health Corporation  29.520000   
104    EIX                               Edison International  44.849998   
65     CMG                             Chipotle Mexican Grill  59.000000   
95     JNJ                                  Johnson & Johnson  68.000000   
73       F                                 Ford Motor Company   8.330000   
64     MET                                            MetLife  52.317291   
17     JCI                 Johnson Controls Internat

In [33]:
wordsList = np.load('wordsList.npy')
print('Loaded the word list!')
wordsList = wordsList.tolist() #Originally loaded as numpy array
wordsList = [word.decode('UTF-8') for word in wordsList] #Encode words as UTF-8

Loaded the word list!


In [34]:
wordVectors = np.load('wordVectors.npy')
print ('Loaded the word vectors!')
wordVectors = np.load('wordVectors.npy')

Loaded the word vectors!


In [35]:
print(len(wordsList))
len(wordVectors)

400000


400000

In [36]:
titleTrain = df_train['Content']
yTrain = df_train['Diff']
titleTest = df_test['Content']
yTest = df_test['Diff']

In [15]:
len(yTrain)# = df_train['Diff']
#yTest = df_test['Diff']

256

In [139]:
yList=[]
YTeList= yTest.tolist()
for i in range(len(YTeList)):
    yList.append([YTeList[i]])

In [140]:
yTest = np.array(yList)

In [40]:
len(yTest)

640

In [38]:
import re
strip_special_chars= re.compile("[^A-Za-z0-9 ]+")

def cleanSen(string):
    string= string.replace("<br />"," ")
    return re.sub(strip_special_chars,"", string)

In [238]:
def sent2Vect(arr):
    retData=[]
    list = arr.tolist()
    for idx in range(len(titleTrainList)):
    row = cleanSen(titleTrainList[idx]).split(" ")
    sent = np.zeros((3000), dtype='int32')
        for word in range(len(row)):    
            ctr = ctr +1
            try:
                sent[word] = wordsList.index(row[word])
            except ValueError:
                sent[word] = 399999 #Vector for unkown words
        retData.append(sent.tolist())
    return np.array(retData)


IndentationError: expected an indented block (<ipython-input-238-635daa16dee4>, line 5)

In [41]:
data = []
ctr = 0
titleTrainList = titleTrain.tolist()
for idx in range(len(titleTrainList)):
    row = cleanSen(titleTrainList[idx]).split(" ")
    sent = np.zeros((3000), dtype='int32')
    for word in range(len(row)):    
        ctr = ctr +1
        try:
            sent[word] = wordsList.index(row[word])
        except ValueError:
            sent[word] = 399999 #Vector for unkown words
    data.append(sent.tolist())
xTrain = np.array(data)
yTrain= to_categorical(yTrain,nb_classes=2)

KeyboardInterrupt: 

In [43]:
xTrain

array([[399999, 399999, 399999, ...,      0,      0,      0],
       [399999, 399999, 399999, ...,      0,      0,      0],
       [399999, 399999, 399999, ...,      0,      0,      0],
       ...,
       [399999, 399999, 399999, ...,      0,      0,      0],
       [399999, 399999, 399999, ...,      0,      0,      0],
       [399999, 399999,    311, ...,      0,      0,      0]])

In [223]:
for id in range(len(xTrain)):
    xTrain[]=xTrain[id][3:]


ValueError: could not broadcast input array from shape (2997) into shape (3000)

In [ ]:
data = []
ctrT = 0
titleTestList = titleTest.tolist()
for idx in range(len(titleTestList)):
    row = cleanSen(titleTestList[idx]).split(" ")
    sent = np.zeros((3000), dtype='int32')
    for word in range(len(row)):    
        ctrT = ctrT +1
        try:
            sent[word] = wordsList.index(row[word])
        except ValueError:
            sent[word] = 399999 #Vector for unkown words
    data.append(sent.tolist())
xTest = np.array(data)
yTest= to_categorical(yTest,nb_classes=2)

In [44]:
print(xTest.shape)
print(xTrain.shape)
print(yTest.shape)
print(yTrain.shape)

(64, 3000)
(256, 3000)
(640,)
(2560,)


In [169]:
wordVectors

array([[ 0.       ,  0.       ,  0.       , ...,  0.       ,  0.       ,
         0.       ],
       [ 0.013441 ,  0.23682  , -0.16899  , ..., -0.56657  ,  0.044691 ,
         0.30392  ],
       [ 0.15164  ,  0.30177  , -0.16763  , ..., -0.35652  ,  0.016413 ,
         0.10216  ],
       ...,
       [-0.51181  ,  0.058706 ,  1.0913   , ..., -0.25003  , -1.125    ,
         1.5863   ],
       [-0.75898  , -0.47426  ,  0.4737   , ...,  0.78954  , -0.014116 ,
         0.6448   ],
       [-0.79149  ,  0.86617  ,  0.11998  , ..., -0.29996  , -0.0063003,
         0.3954   ]], dtype=float32)

In [ ]:
import tensorflow as tf
tf.reset_default_graph()
#trainVec=tf.nn.embedding_lookup(wordVectors,xTrain)
#testVec=tf.nn.embedding_lookup(wordVectors,xTest)
#print (trainVec)
#tflearn.config.init_training_mode()
net= tflearn.input_data([None,3000])
net= tflearn.embedding(net,input_dim=400000,output_dim=50, trainable=False, name="EmbeddingLayer")
net= tflearn.lstm(net,50,dropout=0.8)
net= tflearn.fully_connected(net,2,activation='sigmoid')
net= tflearn.regression(net,optimizer='adam',learning_rate=0.0001,loss='categorical_crossentropy')

model = tflearn.DNN(net,tensorboard_verbose=1)
# Retrieve embedding layer weights (only a single weight matrix, so index is 0)
embeddingWeights = tflearn.get_layer_variables_by_name('EmbeddingLayer')[0]
# Assign your own weights (for example, a numpy array [input_dim, output_dim])
model.set_weights(embeddingWeights, wordVectors)


3385   -0.0
3218    1.0
1217    1.0
3350   -0.0
3322   -0.0
1072   -0.0
2260   -0.0
2727   -0.0
2654    1.0
1181    1.0
281    -0.0
1840   -0.0
2845   -0.0
2030    1.0
1690   -0.0
3493    1.0
1146   -0.0
283     1.0
1800   -0.0
2335    1.0
2186    1.0
1956    1.0
489     1.0
2341    1.0
3861   -0.0
2688    1.0
385     1.0
504     1.0
468    -0.0
2152    1.0
       ... 
3818   -0.0
26     -0.0
713     1.0
3430    1.0
1509   -0.0
1500   -0.0
3714   -0.0
3883   -0.0
213     1.0
4100   -0.0
2269   -0.0
473    -0.0
2392    1.0
298    -0.0
3512    1.0
265    -0.0
3971   -0.0
1810   -0.0
2014    1.0
2262    1.0
4015    1.0
635     1.0
1825    1.0
3351    1.0
3907   -0.0
2856   -0.0
3855    1.0
3170   -0.0
608    -0.0
3591   -0.0
Name: Diff, Length: 3200, dtype: float64

In [ ]:
model.fit(xTrain,yTrain,validation_set=(xTest,yTest), show_metric=True,batch_size=32)

In [23]:
title = 'Exxon Mobil offers plan to end Alaska dispute'
row = title.split(" ")
sent = np.zeros((3000), dtype='int32')
for word in range(len(row)):    
    ctrT = ctrT +1
    try:
        sent[word] = wordsList.index(row[word])
    except ValueError:
        sent[word] = 399999 #Vector for unkown words

#print(sent.tolist())
model.predict([sent.tolist()])

array([[0.5072881 , 0.49263236]], dtype=float32)

In [105]:
title = 'Oracle falls 11% on strong decline; Circuit City shares ease, CarMax hits all-time low'
print(cleanSen(title))
row = cleanSen(title).split(" ")
sent = np.zeros((15), dtype='int32')
for word in range(len(row)):    
    ctrT = ctrT +1
    try:
        sent[word] = wordsList.index(row[word])
    except ValueError:
        sent[word] = 399999 #Vector for unkown words

print(sent.tolist())
model.predict([sent.tolist()])

Oracle falls 11 on strong decline Circuit City shares ease CarMax hits alltime low
[399999, 2625, 418, 13, 562, 1943, 399999, 399999, 544, 3586, 399999, 2042, 220145, 653, 0]


array([[1.]], dtype=float32)

In [88]:
wordsList.index('bad')

978

model.predict('DB does bad in first quarter')